project:
  type: website

website:
  title: "multised (refined)"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/seafood-hazards/multised-refined
        aria-label: GitHub
    left:
      - text: "Home"
        href: index.qmd
      - text: "DB Schema"
        href: db-schema-refined.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: kable
    include-in-header: header.html

execute:
  echo: false
  warning: false
  message: false
