project:
  type: website
  pre-render: download_resources.R
  resources:
    - "*.sqlite"
    - libs/

website:
  title: "multised (refined)"
  navbar:
    search: true
    right:
      - icon: github
        href: https://github.com/seafood-hazards/multised-refined
        aria-label: GitHub
    left:
      - text: "Home"
        href: index.qmd
      - text: "DB Design"
        menu:
          - text: "DB Schema"
            href: db-schema-refined.qmd
          - text: "Tables"
            href: refined-tables.qmd
      - text: "Background"
        menu:
          - text: "Global Background"
            href: background.qmd
          - text: "Grain-Size-Normalised Background"
            href: background-gsnorm.qmd
          - text: "Distribution-Mixture Background"
            href: background-mixture.qmd
          - text: "Pressure-Based Background"
            href: background-pressure.qmd
          - text: "Pressure Controls"
            href: pressure-controls.qmd
          - text: "Background Map"
            href: background-map.qmd
          - text: "Background Summary"
            href: background-summary.qmd
      - text: "Enrichment"
        menu:
          - text: "Enrichment Factor"
            href: background-ef.qmd
          - text: "Regression Normalisation"
            href: background-regression.qmd
          - text: "Pristine Classification"
            href: background-pristine.qmd
          - text: "Enrichment Map"
            href: enrichment-map.qmd
          - text: "Enrichment Summary"
            href: enrichment-summary.qmd
      - text: "Method Revisions"
        href: method-revisions.qmd
      - text: "EFSA Submission"
        menu:
          - text: "EFSA Format v1"
            href: efsa-format.qmd
          - text: "EFSA Submission v1"
            href: efsa-submission.qmd
          - text: "EFSA Format v2"
            href: efsa-format-v2.qmd
          - text: "EFSA Submission v2"
            href: efsa-submission-v2.qmd
      - text: "Downloads"
        menu:
          - text: "Database"
            href: download-database.qmd
          - text: "Dataset"
            href: download-dataset.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    df-print: kable
    include-in-header: header.html

execute:
  echo: false
  warning: false
  message: false
